#!/usr/bin/expect -f

set timeout 20
set user "example_user"
set pass "example_pass" # If you have special characters you may need an escape \
set host "192.168.11.1"

spawn ssh -o StrictHostKeyChecking=no $user@$host

sleep 2

expect "Password for"
send "$pass\r"

sleep 2

expect "Enter an option:" # Stupid menu prompt
send "8\r"

sleep 2

expect "/root"
send "arp -a\r"

sleep 2

expect "/root"
puts $expect_out(buffer)

sleep 2

send "exit\r"
expect eof
